name: Continuous Release

on:
  workflow_dispatch:
  schedule:
    # Run every five minutes.
    - cron: '*/5 * * * *'

jobs:
  trigger_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: During business hours?
        # Check to see if it is a weekday between 8am and 8pm in "America/New_York" timezone.
        # Times taken from RunsDuringBusinessHours.php::isCurrentlyDuringBusinessHours()
        run: |
            export TZ="America/New_York"
            echo "Current time: $(date)"
            if [ $(date +%u) -lt 6 ] && [ $(date +%H) -ge 8 ] && [ $(date +%H) -lt 20 ]; then
              echo "It is during business hours."
              echo "BUSINESS_HOURS=true" >> $GITHUB_ENV
            else
              echo "It is not during business hours."
              echo "BUSINESS_HOURS=false" >> $GITHUB_ENV
            fi

      - name: Content Release running?
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            RUNNING_WORKFLOWS=$(gh run list --workflow "Content Release" --json status --jq '.[] | select(.status == "in_progress")')
            if [ -n "$RUNNING_WORKFLOWS" ]; then
                echo "Content Release is already running."
                echo "RELEASE_WORKFLOW_RUNNING=true" >> $GITHUB_ENV
            else
                echo "Content Release is not running."
                echo "RELEASE_WORKFLOW_RUNNING=false" >> $GITHUB_ENV
            fi

      - name: Run Content Release
        if: env.BUSINESS_HOURS == 'true' && env.RELEASE_WORKFLOW_RUNNING == 'false'
        run: |
          gh workflow run content_release.yml
          
