name: Content Release

on:
  repository_dispatch:
    types: [content-release]
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Wait for 15 seconds
        run: sleep 200
